# Setup
title: Gustavo Vergara
tagline: Dev
url: https://gustavovergara.github.io
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

ga_analytics: G-EEX6L63TQF

# Specify the author for blog posts
author:
  name: Gustavo Vergara
  url: https://github.com/GustavoVergara
  email: gustavovergara.dev@gmail.com

# Custom vars
version: 3.0.0

# Navigation Bar
navigationItems:
  - title: Posts
    path: /archive

  - title: About
    path: /about
